# Generated by Django 6.0 on 2026-01-03 23:15

import core.validators
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notification_days',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='whatsapp_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='alias',
            field=models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(blank=True, default='', max_length=10, validators=[core.validators.validar_placa_colombiana]),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['owner', 'created_at'], name='core_vehicl_owner_i_b87a8b_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['plate'], name='core_vehicl_plate_c3e968_idx'),
        ),
    ]
