# Generated by Django 6.0 on 2026-01-04 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_email_notifications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Identificador único (ej: simit, runt_placa).', unique=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('icon', models.CharField(default='bi-link-45deg', help_text='Clase de Bootstrap Icons. Ej: bi-receipt-cutoff', max_length=80, validators=[django.core.validators.RegexValidator(message='El icono debe ser una clase Bootstrap Icons tipo: bi-receipt-cutoff', regex='^bi-[a-z0-9-]+$')])),
                ('note', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servicio oficial',
                'verbose_name_plural': 'Servicios oficiales',
                'ordering': ['sort_order', 'title'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='core_offici_is_acti_664fb9_idx')],
            },
        ),
    ]
