# Generated by Django 6.0 on 2026-01-04 08:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seed_official_services'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('archivo', models.FileField(max_length=500, upload_to='documentos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'heic'])])),
                ('tipo', models.CharField(choices=[('SOAT', 'SOAT'), ('TECNO', 'Tecnomecánica'), ('SEGURO', 'Seguro'), ('POLIZA', 'Póliza'), ('FACTURA', 'Factura'), ('OTRO', 'Otro')], max_length=20)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fecha_documento', models.DateField(blank=True, null=True)),
                ('es_valido', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('vigencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.vigencia')),
            ],
            options={
                'ordering': ['-fecha_documento', '-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='FCMToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('device_type', models.CharField(choices=[('ANDROID', 'Android'), ('IOS', 'iOS'), ('WEB', 'Web')], default='ANDROID', max_length=20)),
                ('device_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_active'], name='core_fcmtok_user_id_2001a5_idx'), models.Index(fields=['token'], name='core_fcmtok_token_4ccf37_idx')],
            },
        ),
    ]
