# Generated by Django 6.0 on 2026-01-03 04:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp')], max_length=12)),
                ('status', models.CharField(choices=[('SENT', 'Enviado'), ('FAILED', 'Fallido'), ('SKIPPED', 'Omitido')], max_length=10)),
                ('message', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('vigencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='core.vigencia')),
            ],
        ),
    ]
